services:
  jekyll:
    build: .
    container_name: jekyll_blog
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --watch --force_polling --host 0.0.0.0 --livereload